name: Java CI/CD for 2048 Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: game2048-war
          path: target/game2048.war

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: game2048-war

      - name: Deploy to Tomcat
        run: cp game2048.war /usr/local/tomcat/webapps/
