name: Java CI/CD for 2048 Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Check if WAR file exists
        run: |
          if [ ! -f "target/game2048.war" ]; then
            echo "WAR file does not exist. Build failed or incorrect packaging configuration."
            exit 1
          fi

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: game2048-war
          path: target/game2048.war

      - name: Confirm artifact upload
        run: echo "Artifact uploaded successfully"

  deploy:
    runs-on: self-hosted

    needs: build

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: game2048-war

      - name: Confirm artifact download
        run: echo "Artifact downloaded successfully"

      - name: Deploy to Tomcat
        run: |
          cp game2048.war /usr/local/tomcat/webapps/
